baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = "Zz1's temporary blog"
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.zh]
  languageName = 'Chinese'
  contentDir = 'content/content.zh'
  weight = 1

[languages.en]
  languageName = 'English'
  contentDir = 'content/content.en'
  weight = 2

[languages.ru]
  languageName = 'Russian'
  contentDir = 'content/content.ru'
  weight = 3
